build: false

environment:

  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  # Issues have been encountered with installing numpy and scipy on
  # AppVeyor e.g.
  # http://tjelvarolsson.com/blog/how-to-continuously-test-your-python-code-on-windows-using-appveyor/
  # Miniconda is recommended as the way to install these. See also:
  # https://github.com/appveyor/ci/issues/359
  # The following adopts approaches suggested in the above links.
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --prepend channels conda-forge
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION%"
  - activate test-environment

  # Install py.test explicitly else Travis CI will use the one in its
  # virtualenv which can't use the Miniconda environment.
  - conda install pytest behave
  # Install packages needed for testing recipy.
  - conda install python-dateutil pyyaml numpy git
  # Install packages that recipy can log.
  - conda install matplotlib
  - conda install pandas pytables xlrd xlwt
  - conda install lxml
  - conda install beautifulsoup4
  - conda install pillow
  - conda install scikit-learn
  - conda install scikit-image
  - pip install nibabel
  - conda install gdal imageio tifffile
  # Copy matplotlib configuration so it does not try and plot to 
  # screen, which can cause matplotlib tests to fail.
  - copy integration_test\packages\matplotlibrc .
    # Install recipy.
  - pip install .
  # Print the environment.
  - which python
  - which pip
  - which py.test
  - py.test --version
  - pip freeze

test_script:
  # Run py.test with 'v' (verbose) to show test function names and  
  # 'rs' to show reasons for skipped tests
  - py.test -v -rs integration_test
