build: false

environment:

  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64
    - PYTHON_VERSION: 3.4
      MINICONDA: C:\Miniconda3-x64
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda3-x64
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3-x64

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  # Issues have been encountered with installing numpy and scipy on
  # AppVeyor e.g.
  # http://tjelvarolsson.com/blog/how-to-continuously-test-your-python-code-on-windows-using-appveyor/
  # Miniconda is recommended as the way to install these. See also:
  # https://github.com/appveyor/ci/issues/359
  # The following adopts approaches suggested in the above links.
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --prepend channels conda-forge
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION%
    pytest
    python-dateutil pyyaml numpy git
    matplotlib
    pandas pytables xlrd xlwt
    lxml
    beautifulsoup4
    pillow
    scikit-learn
    scikit-image
    nibabel
    gdal imageio tifffile xarray rasterio netCDF4
    iris
    joblib"
  - activate test-environment
  # Install dependencies for keras if the python version allows it
  - set TEMP_VAR=
  - IF %PYTHON_VERSION%==3.5 set TEMP_VAR='1'
  - IF %PYTHON_VERSION%==3.6 set TEMP_VAR='1'
  - IF %TEMP_VAR%=='1' (conda install tensorflow keras>=2.2.4)
  # Copy matplotlib configuration so it does not try and plot to 
  # screen, which can cause matplotlib tests to fail.
  - copy integration_test\packages\matplotlibrc .
    # Install recipy.
  - pip install .
  # Print the environment.
  - which python
  - which pip
  - which py.test
  - py.test --version
  - python --version
  - pip freeze

test_script:
  # Run py.test with 'v' (verbose) to show test function names and  
  # 'rs' to show reasons for skipped tests
  - py.test -v -rs integration_test
